restructure by pyscoffold

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,83 +1,40 @@
-# After changing this file, check it on:
-#   http://lint.travis-ci.org/
-#
+# Travis configuration file using the build matrix feature
+# Read more under http://docs.travis-ci.com/user/build-configuration/
+# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!
+
 sudo: false
-
 language: python
-
-cache:
-  directories:
-    - $HOME/.cache/pip
-
+virtualenv:
+  system_site_packages: false
 matrix:
+  fast_finish: true
   include:
-    - os: linux
-      python: 2.7
-      env:
-      - OPTIONAL_DEPS=1
-      - BUILD_DOCS=0
-      - DEPLOY_DOCS=0
-    - os: linux
-      python: 2.7
-      env:
-      - OPTIONAL_DEPS=1
-      - MINIMUM_REQUIREMENTS=1
-      - REPORT_COVERAGE=1
-    - os: linux
-      python: 3.6
-      env: OPTIONAL_DEPS=1
-    - os: linux
-      python: 3.6
-      env:
-      - OPTIONAL_DEPS=1
-      - MINIMUM_REQUIREMENTS=1
-    - os: osx
-      osx_image: xcode7.3
-      language: generic
-      env:
-      - TRAVIS_PYTHON_VERSION=3.6.0
-      - OPTIONAL_DEPS=1
-      - OSX_PKG_ENV=miniconda
-    - os: osx
-      language: generic
-      env: TRAVIS_PYTHON_VERSION=3.6
-    - python: 2.7
-    - python: 3.5
     - python: 3.6
-
-before_install:
-  # prepare the system to install prerequisites or dependencies
-  - source tools/travis/before_install.sh
-  - uname -a
-  - printenv
-  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
-      source tools/travis/osx_install.sh;
-    else
-      source tools/travis/linux_install.sh;
-    fi
-
+      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="true"
+    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
 install:
-  # install required packages
-  - pip install --upgrade pip
-  - pip install --retries 3 ${PIP_FLAGS} -r requirements.txt
-  - if [[ "${OPTIONAL_DEPS}" == 1 ]]; then
-      pip install --retries 3 ${PIP_FLAGS} -r requirements/extras.txt;
-    fi
-  - printenv PWD
-  # install pgpy
-  - pip install .
-  # show what's installed
-  - python --version
-  - pip list
-
+  - source tests/travis_install.sh
+  - pip install -r requirements.txt
+  # ^  DEPRECATION WARNING:
+  # The automatic creation of a `requirements.txt` file is deprecated.
+  # See `Dependency Management` in the docs for other options.
+before_script:
+  - git config --global user.email "luk036@gmail.com"
+  - git config --global user.name "Wai-Shing Luk"
 script:
-  - pytest --cov=./
-
+  - python setup.py develop
+  - tox
+  - |
+    if [[ "$COVERAGE" == "true" ]]; then
+      pre-commit install
+      pre-commit run --all-files
+      python setup.py test --addopts --cov=src/
+    fi
 after_success:
-  - codecov;
-
-notifications:
-  email: false
-  slack:
-    rooms:
-      - loksu:jErzuILLSNn9qGYkkILvBwje#ellpy
+  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
+after_script:
+  - travis-cleanup
+cache:
+  pip: true
+  directories:
+    - $HOME/miniconda
